### ISSUE TITLE
replace test DB with real data from students

### ISSUE THREAD

**Issue by alexkaessner** [varusgarcia/Design-History-InfoVis#13]

**Comment by alexkaessner** [comment]
Data is comming at the 26.02.

**Comment by alexkaessner** [comment]
@natael We've started moving the test db to the real db (see **real-database** branch). Currently there's [the problem](https://github.com/varusgarcia/Design-History-InfoVis/issues/21) with the JSON format and d3 has a problem with `.selectAll` for the connections. Do you have any idea what the problem is??

**Comment by natael** [comment]
there was a problem with the integer-only id-names. "1", "2", "3" - I prepended "node-" to all ids which fixed the problem.

**Comment by alexkaessner** [comment]
@natael Thanks!! :ok_hand:
