### ISSUE TITLE
multiple edges

### ISSUE THREAD

**Issue by natael** [varusgarcia/Design-History-InfoVis#15]
we need a way to display multiple edges between the nodes.

example:
A + B are connected with the following edges: 
1. "Ehepartner"
2. "Inspiriert durch"
3. "Freundschaft"

we could add all weights together (like 3 +  2 + 3) and increase the stroke width or display several edges.
(or display the edges with a mouseover)

**Comment by alexkaessner** [comment]
So it's allowed to add multiple connections/edges between 2 nodes??

**Comment by natael** [comment]
jup

**Comment by alexkaessner** [comment]
Is this issue still relevant? I mean technically we support this right?
