### ISSUE TITLE
API Endpoint

### ISSUE THREAD

**Issue by natael** [varusgarcia/Design-History-InfoVis#21]
http://designgeschichte.fh-potsdam.de/nodes
-> get all nodes

http://designgeschichte.fh-potsdam.de/edges
-> get all edges

http://designgeschichte.fh-potsdam.de/edge/types
-> get all edge types (for edge description or weights)

http://designgeschichte.fh-potsdam.de/tags
-> get all tags

http://designgeschichte.fh-potsdam.de/tag/{id}
-> get all nodes by tag

tag example:
- Pokémon (id: 3)
  - Pikachu (id: 77)
  - Bisasam (id: 78)
  - Mew (id: 79)

http://designgeschichte.fh-potsdam.de/tag/3
-> would display all nodes with tag for id 3 and its child tags (1 level deep only)

http://designgeschichte.fh-potsdam.de/tag/77
-> would only show nodes which are tagged with "Pikachu"

**Comment by natael** [comment]
access-control origin is set to *, you can use it as a public api now.

example:

``` js
fetch('http://designgeschichte.fh-potsdam.de/nodes').then(function(res) { 
  return res.json(); 
})
.then(function(json) {
  console.log(json);
});
```

**Comment by alexkaessner** [comment]
@natael Could you please remove the `{"nodes":` (and so on) from the beginning of the json files? We don't know how to get into the json array thing. :smirk:

**Comment by natael** [comment]
see commit 325f68e
