### ISSUE TITLE
Looks good.

### ISSUE THREAD

**Issue by natael** [varusgarcia/Design-History-InfoVis#23]
![bildschirmfoto 2016-02-13 um 15 17 20](https://cloud.githubusercontent.com/assets/1047513/13028138/5d0b5d24-d266-11e5-99b7-d4e5e4ed0381.png)

xD

**Comment by alexkaessner** [comment]
Well…yeah…that's a thing we have to improve! :grin:

**Comment by clementcopper** [comment]
NICE!

**Comment by alexkaessner** [comment]
7c63898bca1ac5208ee4d75a4af8a81e6d060123
