### ISSUE TITLE
better date formatting (without time)

### ISSUE THREAD

**Issue by alexkaessner** [varusgarcia/Design-History-InfoVis#25]
@natael Could you may remove the time code (`00:00:00`) from the date formatting. :wink:

**Comment by natael** [comment]
you can convert it to a date object.

``` js
new Date(d.date_birth)
```

and then you have several methods: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

``` js
new Date('1941-10-31 00:00:00').getFullYear() // 1941
new Date('1941-10-31 00:00:00').getMonth() + 1 // 10
new Date('1941-10-31 00:00:00').getDate() // 31
```

getMonth() => months are from 0 - 11 ... so add one up
getDay() method is there to get the day of the week -> for example "it was a monday", its quiet confusing, so you need to use the getDate() method, which will return the right value.

the best option is to use a library like [momentjs](http://momentjs.com/)

``` js
moment('1941-10-31 00:00:00').format('DD.MM.YYYY') // "31.10.1941"
```
