### ISSUE TITLE
update syntax for edges.json

### ISSUE THREAD

**Issue by alexkaessner** [varusgarcia/Design-History-InfoVis#27]
Hey @natael,
could you please update the edges.json syntax. To use the [force layout](https://github.com/mbostock/d3/wiki/Force-Layout#links) from d3 the `start_id` and `node_id` in edges need to be formatted like this: `"target": 82` and `"source": 74`

**Please without the quotation marks! Otherwise it doesn't work. Thanks!**

**Comment by natael** [comment]
i don't get it. code example?

**Comment by alexkaessner** [comment]
The D3 force layout generates the edges for every node based on the `target` and `source` object in JSON. I can't change the naming (don't know why). So the JSON must be formatted something similar to this test: https://github.com/varusgarcia/Design-History-InfoVis/blob/real-database/test-db/connection1.json

**Comment by alexkaessner** [comment]
@natael Alvaro converted the complete JSON file into a [second one](https://github.com/varusgarcia/Design-History-InfoVis/blob/real-database/test-db/connection2.json) for testing. But strangely it doesn't work anymore. The formatting seems to be the same. Any idea what this error could cause?

**Comment by varusgarcia** [comment]
Hey @natael hab mal die [Json](https://raw.githubusercontent.com/varusgarcia/Design-History-InfoVis/real-database/test-db/connection2.json) durch ein [json editor ](http://www.jsoneditoronline.org/) analysiert und hab gemerkt dass es ins gesamt 1187 Verbindungen gibt, die Lezte hat aber die ID 1308.
Das könnte nämlich unser Problem sein, ich kriege die Message : “Cannot read property 'weight' of undefined", [Hier](http://stackoverflow.com/questions/11357974/d3-js-cannot-read-property-weight-of-undefined-when-manually-defining-both) meint einer :

> the reason for this could be the assignment of an out-of-range source/target. E.g. you have 10 nodes and you assign the target to be the 11-th indexed node.

**Comment by natael** [comment]
die elemente haben einfach kein weight property - wenn d3 force graph so einen wert erwartet, muss der auch gesetzt sein.

``` js
{
  id: "2",
  target: 82,
  type_id: "12",
  edge_src: null,
  source: 74,
  weight: 1
},
```

**Comment by alexkaessner** [comment]
Also die `weight` property sollte das problem lösen? Wollen wir die `type_id` als `weight` definieren oder sind das unterschiedliche Sachen?

**Comment by natael** [comment]
type_id ist eine referenzierung auf http://designgeschichte.fh-potsdam.de/edge/types, hier ist erst das tatsächliche weight, title, description etc.. eigentlich war das halt so gedacht, dass ihr die types ladet und die dann richtig mapped. da wir sonst jedesmal in jedes objekt die type title etc. mitschleppen und das edges json sehr viel doppelte inhalte enthält und damit unnötig die dateigröße erhöht.

**Comment by alexkaessner** [comment]
Ah ja okay. Na dann lassen wir die `type_id` und fügen noch die `weight` hinzu?

**Comment by natael** [comment]
ich weiß nicht in welchem zusammenhang weight gebraucht wird. bei den nodes macht es ja sinn, weil sich die dann entsprechend vergrößern, wenn das ne standard-einstellung von force graph ist. wieso der die bei den verbindungen laden will, weiß ich nicht.

https://github.com/mbostock/d3/wiki/Force-Layout#nodes

hier braucht das objekt weight, und ich geh davon aus, dass sich der fehler eigentlich auf die node.json bezieht.

https://github.com/mbostock/d3/wiki/Force-Layout#links

hier gibt es nur source und target, und die sind im objekt ja enthalten.

**Comment by alexkaessner** [comment]
Aber momentan passt er ja die Größe der Nodes basierend auf den Verbindungen an. Und auch bei diesem Beispiel aus Stackoverflow: http://jsfiddle.net/nbhu2L76/3/ gibt es nur `source` und `target` als properties, die anderen sind alle custom.

**Comment by natael** [comment]
"if they are not set, suitable defaults will be initialized"

weight wird ja anscheinend automatisch von d3 gesetzt, ich weiß halt nicht, wo der fehler geworfen wird.
passiert das schon in der test.html?

**Comment by alexkaessner** [comment]
Ja genau, wir haben erst mal in der `test.html` gearbeitet und wollen das dann übertragen…

**Comment by natael** [comment]
so wie ich das verstehe, erstellt d3 bei den nodes einen eigenen index.
ich hab versucht den in den nodes hinzuzufügen, so dass d3 keinen "default" index setzt, aber das ist nicht der fall. die loopen die elemente durch und setzen einen eigenen index und dann stimmen die target und source werte nicht.

dadurch werden die referenzierungen natürlich fehlerhaft.

versteh leider nicht, wieso das so gemacht wurde - weil das völlig unnötig ist.

ich kenn im moment keine lösung, ohne das ALLE ids irgendwie neu bestimmt werden müssen und das ist nicht wirklich einfach.

s. https://groups.google.com/forum/#!topic/d3-js/LWuhBeEipz4
http://stackoverflow.com/questions/23986466/d3-force-layout-linking-nodes-by-name-instead-of-index

**Comment by alexkaessner** [comment]
Also gibt es keine richtige Lösung für das Problem?

**Comment by natael** [comment]
der lösungsansatz steht in dem zweiten link.

ich hab euch nen lauffähigen stand zusammengebaut, inkl. strichstärke der verbindungslinien.

s. commit 4d3b09f.
