### ISSUE TITLE
multiple sources for nodes

### ISSUE THREAD

**Issue by alexkaessner** [varusgarcia/Design-History-InfoVis#31]
Wie Philip Zerweck [auf Incom](https://incom.org/post/166642) schrieb:

> die Quellen in der Vita werden ohne Trennung als ein einziger Hyperlink dargestellt, obwohl es mehrere unterschiedliche Quellen und Links sind. (Beispiel: Colani)

@natael Können wir da vielleicht auch den Markdown Syntax als HTML parsen?

**Comment by natael** [comment]
gibt nun ein neues feld "source_html", ähnlich wie "vita_html".
