### ISSUE TITLE
database marker for unknown/null birth- and death-year

### ISSUE THREAD

**Issue by alexkaessner** [varusgarcia/Design-History-InfoVis#32]
Wie Philip Zerweck [auf Incom](https://incom.org/post/166642) schrieb:

> wir brauchen unbedingt in der Datenbank einen dezidierten Marker / Zeiger für unbekannte Daten, beziehungsweise "lebt noch" und entsprechende Anzeigen: "unbekannt" bzw. Zeile "gest. …" weglassen.

**Comment by natael** [comment]
wenn date_birth null ist, ist der designer noch am leben. also dann ist einfach kein datum gesetzt.

wenn inaccurate 1 ist, bedeuted das folgendes:
- nur das jahr war gesetzt
- der benutzer hat platzhalter benutzt xx.xx.1234, x.x.1234 oder ?.?.1234 etc.
- tippfehler oder komische formate 1..12.234 or 19. 05. 1234
- datum alle in die form yyyy-mm-dd gebracht (die schnittstelle gibt nun yyyy/mm/dd aus)

das wurde einmal initial beim import der google sheet liste von philip ausgeführt. und alle daten wurden auf den 01.01. des jahres gesetzt mit dem flag "inaccurate", wenn die oben genannten punkte eingetreten sind.

nach dem import haben die leute alle die daten über den datepicker gepflegt, der am anfang zu fehlern führte, da das feld nicht leer sein durfte - und deshalb der aktuelle tag abgespeichert wurde.

die fehler sollte philip aber alle behoben haben, ich hab ihm ja eine liste von unrealisitischen daten gemacht.

im frontend ist nun eigentlich nur noch der fehler, dass überprüft werden muss, ob date null ist, weil new Date(null) ist der 01.01.1970 (beispielsweise ist der herr joop an dem tag wohl gestorben ^^)

**Comment by alexkaessner** [comment]
Also wenn `date_birth = null` ist, dann lebt er noch oder wie?

**Comment by natael** [comment]
ah, nene ich mein date_death natürlich :D

**Comment by alexkaessner** [comment]
Ich hatte mich schon gewundert :grin:
