### ISSUE TITLE
nodes wiggling (and don't open vita) if you click on them

### ISSUE THREAD

**Issue by alexkaessner** [varusgarcia/Design-History-InfoVis#33]
![gif](https://cloud.githubusercontent.com/assets/6615076/14002992/d313d1d8-f14f-11e5-84b5-66ae9e68675d.gif)

**Comment by natael** [comment]
if you click on a node, you trigger a dragstart event, which calls force.start(), which causes the wiggle.
if you delete the force.start() call, it is still possible to move the nodes on the y-axis.

why should you drag a node anyway? just for fun?

**Comment by alexkaessner** [comment]
@natael Oh thanks for the hint! I will look into this…

I don't exactly know why we implemented this 😂 I think mostly for fun, but also to may reveal a overlapped node.
