### ISSUE TITLE
help: backend link doesnt work now

### ISSUE THREAD

**Issue by jianglanke** [varusgarcia/Design-History-InfoVis#34]
cannot get the nodes, edges and types .json

**Comment by alexkaessner** [comment]
@HarkinTan Hey Harkin, sorry this project isn’t maintained and accessible anymore. Unfortunately the backend is offline and thus can’t be accessed.

**Comment by jianglanke** [comment]
> @HarkinTan Hey Harkin, sorry this project isn’t maintained and accessible anymore. Unfortunately the backend is offline and thus can’t be accessed.

thanks for reply🥰🥺I'm a film history researcher in china. and eager to find a force directed timeline or many-to-many relationship timeline solution and find your perfect project. when i find the backend offline, i try to imagine and guess the structure of json file and object, but i failed it.😭anyway. thanks for your all idea and effort for this project.❤️
