### ISSUE TITLE
connection info popover

### ISSUE THREAD

**Issue by alexkaessner** [varusgarcia/Design-History-InfoVis#6]
- [x] connect Data correctly
- [x] show all informations

Like at this draft from me:
![draft 1](https://cloud.githubusercontent.com/assets/6615076/12170785/7834e0d2-b544-11e5-83c9-b153fe910b3c.png)

**Comment by alexkaessner** [comment]
The [EdgeMaps](https://github.com/nrchtct/edgemaps) Project by Marian Dörk may be interesting for us to look at 😁 : http://mariandoerk.de/edgemaps/

**Comment by alexkaessner** [comment]
@natael Kannst du mal schauen warum die `edges` und `edgetypes` nicht verbunden ist (beim hover auf der Linie kommt kein Inhalt)? Bei mir klappt es irgendwie nicht so richtig und ich weis nicht wieso. 😉

**Comment by natael** [comment]
hab dir nen beispiel gebaut, damit du an die daten kommst.

**Comment by alexkaessner** [comment]
Vielen dank! :ok_hand:
Hatte mich verwundert dass die Edges so anders behandelt werden wie die Nodes. Deswegen hatte das dann auch alles nicht geklappt…
